### ISSUE TITLE
xrayr 启动失败

### ISSUE THREAD

**Issue by xbclub** [Misaka-blog/XrayR-3#4]
环境：ubuntu20 amd64
panic：
```golang
panic: proto: file "config.proto" is already registered
	previously from: "github.com/Misaka-blog/XrayR/app/mydispatcher"
	currently from:  "github.com/xtls/xray-core/app/metrics"
See https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict


goroutine 1 [running]:
google.golang.org/protobuf/reflect/protoregistry.glob..func1({0x30bc620?, 0xc0003575d0?}, {0x30bc620?, 0xc000357610})
	google.golang.org/protobuf@v1.28.0/reflect/protoregistry/registry.go:54 +0x1ee
google.golang.org/protobuf/reflect/protoregistry.(*Files).RegisterFile(0xc00000c030, {0x30d8e80?, 0xc0001a5c00?})
	google.golang.org/protobuf@v1.28.0/reflect/protoregistry/registry.go:128 +0x39c
google.golang.org/protobuf/internal/filedesc.Builder.Build({{0x2635b93, 0x25}, {0x416c080, 0x98, 0x98}, 0x0, 0x1, 0x0, 0x0, {0x30c50f0, ...}, ...})
	google.golang.org/protobuf@v1.28.0/internal/filedesc/build.go:113 +0x1d6
google.golang.org/protobuf/internal/filetype.Builder.Build({{{0x2635b93, 0x25}, {0x416c080, 0x98, 0x98}, 0x0, 0x1, 0x0, 0x0, {0x0, ...}, ...}, ...})
	google.golang.org/protobuf@v1.28.0/internal/filetype/build.go:139 +0x19d
github.com/xtls/xray-core/app/metrics.file_config_proto_init()
	github.com/xtls/xray-core@v1.5.5/app/metrics/config.pb.go:143 +0x198
github.com/xtls/xray-core/app/metrics.init.0()
	github.com/xtls/xray-core@v1.5.5/app/metrics/config.pb.go:111 +0x17
```

**Comment by misakano7545** [comment]
什么版本

**Comment by qthang** [comment]
> 什么版本

version 0.8.1.2, i have same problem

**Comment by xiaole51** [comment]
试了目前在线的所有版本均有相同错误. 无法运行.
AMD & ARM平台都试过问题一样. 
是需要安装什么依赖吗?

**Comment by hhaaeerr** [comment]
确实，我也是这个报错，debian11，换了其他人备份的脚本，安装的0.8.0就不会报错。

**Comment by misakano7545** [comment]
> 确实，我也是这个报错，debian11，换了其他人备份的脚本，安装的0.8.0就不会报错。

等我五一假期研究修理一下

**Comment by misakano7545** [comment]
修好了，项目地址：https://github.com/Misaka-blog/XrayR
